#!/bin/sh

current=$(pwd)

function link_dotfile {
  ln -s $current/$1 ~/.$1
  echo ".$1 linked to ~/.$1."
}

function move_and_link_dotfile {
  mv ~/.$1 ~/.$1.jahuang.old
  echo ".$1 backed up to .$1.jahuang.old"
  link_dotfile $1
}

files=(zshrc vimrc zlogin zshenv tmux.conf railsrc)
for file in "${files[@]}"
do
  if [ -f ~/.$file ]; then
    while true; do
      read -p "Do you wish to overwrite ~/.$file?: (yn) " yn
      case $yn in
        [Yy]* ) 
          move_and_link_dotfile $file
          break;;
        [Nn]* ) 
          echo "$file skipped."
          break;;
        * ) echo "Yes or No only.";;
      esac
    done
  else
    link_dotfile $file
  fi
done
