#!/bin/sh

DOTFILES_DIR=`pwd`
HOME_DIR="$HOME"

function link_dotfile {
  ln -fs $DOTFILES_DIR/$1 $HOME_DIR/.$1
  echo ".$1 linked to $HOME_DIR/.$1."
}

files=(zshrc vimrc zlogin tmux.conf rspec railsrc irbrc gemrc ackrc ctags gitconfig gitmessage)
for file in "${files[@]}"
do
  link_dotfile $file
done

ln -sf $DOTFILES_DIR/vim $HOME_DIR/.vim
